### ISSUE TITLE
Add a script for tracking broken links in the docs

### ISSUE THREAD

**Issue by danieljcafonso** [solidjs/solid-docs#458]
In a chat with @atilafassina we figured out there is a script we can run that will check for broken links on our docs and break the build if there are any.
@atilafassina this issue is here for you to check if you can integrate that.
Thank you ❤️

**Comment by atilafassina** [comment]
We may not need that since [Nitro takes a `prerender` object](https://nitro.unjs.io/config#prerender) with:

```js
{
  prerender: {
    crawlinks: true,
    failOnError: true
  }
}
```

with this we can throw errors on build if a route doesn't load.
At the moment, Nitro doesn't understand `<A>` from `solid-router` so we can't use it.

---

Perhaps instead of adding tests for it, we're better of helping @nksaraf add this feature upstream on Vinxi ?

**Comment by LadyBluenotes** [comment]
@atilafassina is this done now?

**Comment by LadyBluenotes** [comment]
I can close this since Netlify shows logs for this
