### ISSUE TITLE
[Other]:BUN AND SOLID.

### ISSUE THREAD

**Issue by MRgrav** [solidjs/solid-docs#794]
### 📋 Explain your issue

As a developer, I have come to know that solid js is light weight and very fast. Also bun is a new run time environment which is 3x faster than node js. So I was thinking to combine both. 

Do release a version that works with bun.

**Comment by birkskyum** [comment]
@MRgrav , the known compatibility issues are all to be resolved in Bun, not in solid or solid-start. See here:

- https://github.com/oven-sh/bun/issues/3736#issuecomment-2193934709

That being said, you can already now build and deploy quite advanced apps with Bun, without hitting any of these - but they're worth being aware of.

think the issue can be closed in this repo, since this is the docs.

**Comment by LadyBluenotes** [comment]
Closing this issue - thanks @birkskyum for clarifying.
