### ISSUE TITLE
[Request]: Add source code links for API references in documention

### ISSUE THREAD

**Issue by namejiahui** [solidjs/solid-docs#988]
### What is this request related to?

Request

### 📋 Suggested

Maybe all references

### 📋 General description or bullet points

When I was exploring SolidStart yesterday, I encountered a problem related to createResource, and I wanted to check the source code, but after I searched the SolidJS repository, I found that there are two functions in the repository with the same name. 

Although I could figure out which one to check,but I think it would be better to add a link to the API source in the documentation. 

Below, I have provided a simple design suggestion

Before:
![image](https://github.com/user-attachments/assets/e29a940d-fd57-413e-8f49-0034584e8273)
After:
![image](https://github.com/user-attachments/assets/f9deafd4-6019-4e53-88f7-c2a2897fc92b)

**Comment by LadyBluenotes** [comment]
Hi @lilijh thank you for your suggestion!

From my perspective, I don’t recall many, if any, reference docs that provide direct links to the source code in their reference sections. My primary concern is that implementing this would introduce significant overhead for the maintainers. It could also lead users to the wrong areas of the codebase, especially when major, minor, or even bug-fix updates are made. These changes could break the links, misdirecting users and requiring us to reassess and potentially update the links with every push.

Because of these concerns, I’ve decided to close this issue. if you’d like to discuss this further, please feel free to start a conversation in the [Solid discord](https://discord.gg/solidjs) in the docs channel. I’d be happy to continue the discussion there!
